import type {
    MapConnection,
    MapNode,
    MapNodeStatus,
} from "./laboratory-map.types";

export const MAP_NODE_STATUS_LABELS: Record<MapNodeStatus, string> = {
    passed: "Пройдено",
    available: "Доступно",
    locked: "Не пройдено",
};

export const LABORATORY_MAP_NODES: MapNode[] = [
    {
        id: "node-1",
        order: 1,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 1,
        category: "Фішинг",
        status: "passed",
        x: 118,
        y: 317,
    },
    {
        id: "node-2",
        order: 2,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 1,
        category: "Фішинг",
        status: "available",
        x: 298,
        y: 317,
    },
    {
        id: "node-3",
        order: 3,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 1,
        category: "Фішинг",
        status: "locked",
        x: 479,
        y: 317,
    },
    {
        id: "node-4",
        order: 4,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 2,
        category: "Фішинг",
        status: "locked",
        x: 888,
        y: 317,
    },
    {
        id: "node-5",
        order: 5,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 2,
        category: "Фішинг",
        status: "locked",
        x: 396,
        y: 483,
    },
    {
        id: "node-6",
        order: 6,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 2,
        category: "Фішинг",
        status: "locked",
        x: 662,
        y: 483,
    },
    {
        id: "node-7",
        order: 7,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 3,
        category: "Фішинг",
        status: "locked",
        x: 1070,
        y: 483,
    },
    {
        id: "node-8",
        order: 8,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 3,
        category: "Фішинг",
        status: "locked",
        x: 866,
        y: 650,
    },
    {
        id: "node-9",
        order: 9,
        label: "Email фішинг",
        title: "Lorem lorem ipsum lorem ips",
        level: 3,
        category: "Фішинг",
        status: "locked",
        x: 1180,
        y: 650,
    },
];

export const LABORATORY_MAP_CONNECTIONS: MapConnection[] = [
    { from: "node-1", to: "node-2", variant: "solid" },
    { from: "node-2", to: "node-3", variant: "dashed" },
    { from: "node-3", to: "node-4", variant: "faded" },
    { from: "node-5", to: "node-6", variant: "faded" },
    { from: "node-6", to: "node-7", variant: "faded" },
    { from: "node-8", to: "node-9", variant: "faded" },
];
